jenkins:
  systemMessage: "Auto Jenkins config (CASC)"

  numExecutors: 1

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified: {}

jobs:
  - script: |
      pipelineJob('seed-job') {
        definition {
          cps {
            script("""
pipeline {
  agent any
  stages {
    stage('Generate') {
      steps {
        jobDsl targets: 'seed.groovy'
      }
    }
  }
}
""")
          }
        }
      }